const Types = {
  REQUEST_GENERICS: "REQUEST_GENERICS",
  ERROR_GENERICS: "ERROR_GENERICS",

  GET_ALL_ERRORS_SUCESSO: "GET_ALL_ERRORS_SUCESSO",
  ARCHIVE_SELECTED_SUCESSO: "ARCHIVE_SELECTED_SUCESSO",
  GET_ERROR_BY_ID_SUCESSO: "GET_ERROR_BY_ID_SUCESSO",

  SET_SELECTED_ITEM: "SET_SELECTED_ITEM",
  SELECT_ALL: "SELECT_ALL",
  FILTER_AMBIENTE: "FILTER_AMBIENTE",
  CHANGE_ORDER_BY: "CHANGE_ORDER_BY",
  APPLY_FILTER: "APPLY_FILTER",
  GET_USER: "GET_USER"
};

export default Types;
